# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Add the test and development secrets

# Do not keep production secrets in the repository,
# instead read values from the environment.

development:
  secret_key_base: '4b308363cf45849009b06afba7a1ddeed5ca5996f13d0a7f381b45da21bedbd412babe8d31c1f6a6b44c1200c5dbef163b566134bb03d6edf22252c2227cd5da'

test:
  secret_key_base: 'afda48990bc08765d9f37e8e77ea8c1f2024b064340315ae8644905f4d4e9f155ef045efd49a3ec5e53960f4b8fc542e9483684f5d1e151bfb80f433c3818c37'

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
